---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: bopbag
  name: bopbag
---
apiVersion: v1
kind: Secret
metadata:
  name: bopbag-certs
  namespace: bopbag
data:
  cluster.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZOVENDQXgyZ0F3SUJBZ0lVVjNvVVgwQ0FrTlZMTGpEWUpBamY1b1BCUDZ3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VURVBNQTBHQTFVRUF3d0dZbTl3WW1Gbk1CNFhEVEl4TVRBd01qQXlNall6TjFvWERUTXhNRGt6TURBeQpNall6TjFvd0VURVBNQTBHQTFVRUF3d0dZbTl3WW1Gbk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBCk1JSUNDZ0tDQWdFQXNYbWtZQmRqdlFNMnZZdS9hWFhJNVFBYmc0alAxaURkT0pIc1piWXZ2MnlaTzZHbkJZem8KclgvR0xYN0M5RWVFRWUwcTVKLzU1NEtTZHlGMC93aGQwemp0aUpLS3VhTlZRTFpsZExVRGpMUUdaaHJKUFVzYwpwV21wK1FQQVptQ3lPL0VaSUxQaGRUZ3AvdTVxaWQ5UVVuRDFweEZ3OXo0NEVGbExQbW5XR1ZVUFVmb21jc1VLCnI1NWp5SWpid09SN0h3TUgzQnVwdmtUVkhDZUI5eHlQZFVWdkZ2MGZub0dJNkR5eVpsdm5vT21oRld2VW42alQKTm4xdWZPUzdXNDMxUW9JNVBpVjJnZWYxWWFvcVVJeVVJRkpwTVlqWEVraWhMMW81Q1J2K1ZTSnhKUFZ6UFBpZwoyNGkyTDVLRERMRHVQakc3VmZzdERXNVpuQTQ1c2dVbmlrVU1HYXV2WTF3Qk00L28rb0JtS0E5SlNEbHlhbXB0CkdIMjNjZ2FobjhZYTdpQ0tHNDJRd2g3cTR5dXRwRTgrd2oyZEZQNC9yaHQvaUdDZzA1Uk9KUldIR3B3OG1xZkEKUVNpdEZhUjRpWk44OEhCS08rYU1OZjRpTmpvdE5Ob0h5VlpQQy85SU10ellGZ3MyRVpJZXNtWUZuRytDWEMzeAp2dm5HRzhlNW9URTlVYnNEUzNBNVlKRGcySmtiOEtQQTdIQXpjVzExV1pTQytCdXZ0UkpOSFlhY2owdkN2TTRFCmRYWEdFWTVJRkt0b05YWk1ZL3daa3BzeFdmQmRBc0lObElwblI4R3hYWER6WjRIRVJ0Rmg2VzFDendjajFSZ1gKNENIa2plWkZvY2tFWWRwWWpwSHE3Q1JCcEpEWjNqdSs3VzMwYmc2RG1YaHNQRVhFRXBzY0dnVUNBd0VBQWFPQgpoRENCZ1RBMkJnTlZIU01FTHpBdG9SV2tFekFSTVE4d0RRWURWUVFEREFaaWIzQmlZV2VDRkZkNkZGOUFnSkRWClN5NHcyQ1FJMythRHdUK3NNQWtHQTFVZEV3UUNNQUF3Q3dZRFZSMFBCQVFEQWdTd01CMEdBMVVkSlFRV01CUUcKQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBUUJnTlZIUkVFQ1RBSGdnVnViM0p6WlRBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FnRUFoN1ZpdlVtQ0FrcEZFVWdKZTZrYzNQQzA0S09LdEYvaUkyeEFkeE9WdS9QOVN2UXNQOG95CkNwc1ptai9Fb2NYNDQvYytFYWVQb25rdDBZMFJvRGtKTGxMSU5BRytZNmpCc3ZXcGJhV1FMVndwV2lnbEpJRjQKMmNzVk1PU2tneXQya2hQVUdoV0JKL21HV3h6b3prYWNRK0ZCWGE0alVpeGtSbzZ6SFk4Zmt0ZnUrTjVTMlJuRQpsRzhYWXFJMWlEOUJMcmE1Sm5rcmtHeGkzYjYwd1JYd1BadDV2Q2RlRitUY1BCV1RUWS9aeUJnVEZ6Y1VHaWE0CkJQUU5CcmhubWdVLzl5RWZBZFI0bG5yeS9zTVVmemJWbmpKWXNvQU45cSsxZnFlQnJEOWc1dFY5ZDNEcHRFWCsKbmdIQk43WkFHMHBsa2ltckdma0lxRG1lUUJjb2FFYlRjR08xZGxYNXB2TUdsdWtYN0REVVpPTEs5Z20zL3VIdwpaVG9RdUduMnpUUjVhNmdhUXhRM3FBcDAzVzNhTmVFcUNvd25Yb0tyM0l3MDN2TlZBSXdoVkpzZHlaeFZZbjFFCm16WWYyYlR5a3cxNm5JNEM4aXhoSFNqelV6MDVnNEpVMk5naHU5RmhvdkZRc3JVQmRDUlpLbG94MkdnSXl1OFEKMmlKVWFETEp2UDEyMmtlYWZZNHFST0dQZ0tCbkZGdStaYk15N2FNcVhYYTA2WXgzOFo2K29JaERNK2F6TEVLUQphQjNzUzF3RW1sMncycC92K3o3TjgxSFpkSXAvNmdRR1VqanJGZU1abEErT2wvR3lrQTIzUFRycTZLSlBwVjkwCmpnWEdOUTN5N1pBbkRIQWp1WHFhMkswbDdkZnZ2ZWc2UmdROXdZWncraENQOEJ0cGg2QXl4RHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  cluster.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ3hlYVJnRjJPOUF6YTkKaTc5cGRjamxBQnVEaU0vV0lOMDRrZXhsdGkrL2JKazdvYWNGak9pdGY4WXRmc0wwUjRRUjdTcmtuL25uZ3BKMwpJWFQvQ0YzVE9PMklrb3E1bzFWQXRtVjB0UU9NdEFabUdzazlTeHlsYWFuNUE4Qm1ZTEk3OFJrZ3MrRjFPQ24rCjdtcUozMUJTY1BXbkVYRDNQamdRV1VzK2FkWVpWUTlSK2laeXhRcXZubVBJaU52QTVIc2ZBd2ZjRzZtK1JOVWMKSjRIM0hJOTFSVzhXL1IrZWdZam9QTEptVytlZzZhRVZhOVNmcU5NMmZXNTg1THRiamZWQ2dqaytKWGFCNS9WaApxaXBRakpRZ1Vta3hpTmNTU0tFdldqa0pHLzVWSW5FazlYTTgrS0RiaUxZdmtvTU1zTzQrTWJ0Vit5ME5ibG1jCkRqbXlCU2VLUlF3WnE2OWpYQUV6aitqNmdHWW9EMGxJT1hKcWFtMFlmYmR5QnFHZnhocnVJSW9ialpEQ0h1cmoKSzYya1R6N0NQWjBVL2ordUczK0lZS0RUbEU0bEZZY2FuRHlhcDhCQktLMFZwSGlKazN6d2NFbzc1b3cxL2lJMgpPaTAwMmdmSlZrOEwvMGd5M05nV0N6WVJraDZ5WmdXY2I0SmNMZkcrK2NZYng3bWhNVDFSdXdOTGNEbGdrT0RZCm1SdndvOERzY0ROeGJYVlpsSUw0RzYrMUVrMGRocHlQUzhLOHpnUjFkY1lSamtnVXEyZzFka3hqL0JtU216RloKOEYwQ3dnMlVpbWRId2JGZGNQTm5nY1JHMFdIcGJVTFBCeVBWR0JmZ0llU041a1doeVFSaDJsaU9rZXJzSkVHawprTm5lTzc3dGJmUnVEb09aZUd3OFJjUVNteHdhQlFJREFRQUJBb0lDQURqSGFQNVJIVml3T1lna3VJVmQ2SHJUCk1QcEEvL1ZLcUZ2YjI1eWl6OTNYT2FMcFVjMGx5cDhQWFBEYk9EWDgxMVVBNHBNb1YwUm84c0RvVkV6dmVVMEYKVG9FK0dPSFJUb29Za0piby9veTZYNzIwM2lNYzc3by85dUF6QWcvKzZhYmh1SjlNelZtNk1UMWRPM3FHbG1UNQp2SzNKbDdHU0YwK3JzYlh6R0VzY2VuMUlvWnBnVGMzbng1YTFxbENwQ0hiZ2VsaENCV2xaRGpFbXRwNi9aV29vClg2VWtNRVIrdnJWR0RmRlBmK2hzTmx2ckZxaEowK0QvK2lRODdYQWFGNWhDbjF1eGtwdDNBWHRRZko4dWlvbFkKdEV6anNhTW8xMkNWNWQ5ek5FZzZiNlphWEpicUdGU0VCWDFzeXo1NU1JOTNTNjd6WC9PSEZXWW02dkI0VTdDUgpibjZ5dVV1TG5uSXkrTjRmWVVGREZrcmhJWXo5VUhzOHFtQlRqVjcrZ1FhemMwMStwcmVVakJoa2ZxSUp0T3RDCmZwd0Q0b3VaUWtvY1p2N0FlZ2J4RlVCejBFb0JDazkrQ3VHT1pWd21VM25VeFV1L204eERaeUZzVjNqZjlOYVkKTHhHNFdJWEFPQ3pjZ3dFbklHd0tFMFBqTXcxeXRGSWRnSVp4WURDSmd0YVZQdHZDdjVQWE50R3hkQW5PclpSegpFTGxOQ1BJdjFPMEQwR25JbmJiSTZ6YUZwMFYvYlBiY05xNlhQYjNIZTcwTVVGbjZuWTRNRy9vaktVeC9oeS80CnFGb2hMZ3A0MlF3bFRkazNWditRZHh6QzFrZFNaVVJSbXQrTUo5Zi9xVldYZXFBV0ljNExUS2QxbWFtbkRpMFgKRHVoZ0Nud1p2eEJ5WUtNQWtJNmhBb0lCQVFEZHJCMWZpUUNiM05yamdQQmFJNEV5akd4LzVIVVRmUVl1czZIQQpLS0FmMUkzaHhmUS9idVExWjhaSEUrOGxKY0pteFMrTUlLZ1g5M3hKL2V6bm1XZG5zbWxmN0QrVzJoUkJiOEhxCnRacHVMakhTcS82cVhMZnVNbkNBb0drZFRDdlYrQjB6WEdCS1J1cjJkZlhXUVI2bjUyRzdhdTJSTjgzL2NLbVoKaVRBZXNkbS96L0VUTVVNVUt1aGVsNWx6cSs2VTBvTmozdzlVOXNwb21abVZtWGc4OXBmUnFRWWV1TnJ3Q0ZReQpmdzF1YjZkVkNXa1JhVmpFRXU4b3NtL2xCOVJZbVlKRG9ZZDkwZ1hUell5bk5VTHRsWXV6OEVDYnIraldiQnh1CnpPRWZISWpxQjVHY1FFdWRSS210NGtQc2hUZmE4bHdBdVZnZXd3Y1B1aVlrdHY4OUFvSUJBUURNOVdUQ3V2TWIKUUNabXMxd2lZcUllNkVhNW9uNVlpekJFOVhlaVRpTFR1eklNMm1OVUZvaVFPaE5OR2tUWDlyb3RsUmRLczVqVApQbHQ5MndQSjlvdkFtMSttVzZQQ0lYaWlzS0MzWk5DL1hJb2lzNjlyeU1sTHRkYnlaa0p2TVZ2R3hONnBtK3ZjCnBOeUtSU0wvT3o5a2FQUHhYRUFDeWl1UDNySU01ZURiQmR0d3JUU1JMTTlyemZHWHZiTEp4Y0wyUE43SFA3dW4KZjgvZkdOS2sxMDRnbkpXVTNkWG9sdklwUlZGelVrbi9jOHNFMVNteFAyTnJGbUZRMWlkMUF4NmRIMjZwdTlabgpJTWlLcW13MEtNZjFzd2tQcFJxQTBaNmtXcjlhRGNnbmZYeG5hMEdrVnRxNnY2ZGhzSmFaNXQxc2VYT0pWRUpsCnZ4d1E1VjBDT2JKcEFvSUJBR3o4Mkp4R0lkU0FLK2E3V0hFWkQ4YW9vQmZwWFY2dGs4S1djeXFsVHNVWG5vS28KNzBQWTQ3OFdQTGhwcHFUZkFjdkJtM1VNQVZsM1J0YWlVRDQyZ0U3TnUxMThMRytnM1dDbTcvTFVRdzkxQ3U0SAp2bmhJaWU1RlFtY2JkMUwrUm5jM1BEUXFjUFZVRk9ZRWJWQmdTQkJKaFJXK3B2dEZNclVxMFZnNXlUenVPSjlFClA4VXQ3VXNYSlpTTWVOZ1Vhb01sVlpCZTlZelNvZ1gzcnptTWNUK1lCbUVBOTQ5WFY5MjRXcDFSTm10YjNpdkQKS3JOeTFqL2hCMUU5R2lMRFRMWWJFNTdvNWxNSVZmRWpHTXFGTjFqVXRCRk9TSlhEVVhsTFFsZC95QmVoMGZjdQpyWHJqYWNuekhuSHQwM09RdER1aitYUXBySmZEVDg5OXVJOUlvZ2tDZ2dFQVRpREUxZzRabWF1c2Q3MnJRMWhCCjRISStjNGpqakxFU0oxZEMwVlhqcEw1WTU5bGZ2N0FQUXB0QXZFVmxOTVhTVm9uY3BSY3RER2xheXZEdjBzN3UKbXU4ZldQVFp5YWlrcWErV3RCSDBHTjRYc2Y2NHdlZDZCQ2crMVl2eGl4MVBsTWQ2OFVDRWVrbEY0RmRXYmVDUgoyNTYrVHFVUnFYNlRlSFkxZlFFcjQ1R3FBcHVqekNzK3JpT0ZFb2kzWEg3TVFMMFhWdkNPZ2QwUXlrUldGNHdUCk5nODZYZExxTlkxRXBrTE1ONStJb1ozc0o5MXgxU1VLcXNtUE14ZFBWeVZuU0JHeFIzWlkxbHNDMXdqNzBpNHgKZXhGU1JPcDAzZUlLRFRDaWZKdUFUcjFnN0xOUUJHc3ZXYnl3KzJZckltT0V5RkxMbmUvR2w2NXY3bWpnT1hidwo4UUtDQVFFQTE2TzJlSW1Ud3hoZGVETzY2aUlVRTA0RnpLc0tBdHVwS0JGUC9NTUpkRjJJRkFTK0hSQzZPdmpoCkt1dGFadHhoWUxTVVhBdXJwYUtCdFlFajRnZFNGWW9oMmFteW91dVk4MC92dHBLcTRjNVN5WThJMTQyMCtxNkkKZTZaK0U2L2t2Wmpmb2pMV3ZmMWZjbms4MzhhMGU5dTAzNkk3UGV6dk5nOUJTa0ZzRlRWRGZFclJ3cUFrK0wyYgpZeU9FaW9PaUZ6Q2svSWhYVVljVXRUejl3bGpGTEI1dWxHNlA1M1ZxdnMrQWxZcHp4UnF1OWRoOVlpQmJtWGphClh5cUR3Y3JlOWQzZ0hCbTV0bFF1WnRTallQTVkvTkw0QnovbjY4eXFMYXBzeFNMQ0dReFVBZDBwRlpQWGVxNnQKZ1NWNjNJSnZkVHUrZmZvMGE1WlBEQUFDUE5uZm5RPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: v1
kind: Service
metadata:
  name: bopbag-headless
  namespace: bopbag
  labels:
    app: bopbag
spec:
  publishNotReadyAddresses: true
  ports:
  - port: 9000
    name: dqlite
    targetPort: dqlite
  clusterIP: None
  selector:
    app: bopbag
---
apiVersion: v1
kind: Service
metadata:
  name: bopbag-web
  namespace: bopbag
  labels:
    app: bopbag
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web
    nodePort: 32657
    name: web
  selector:
    app: bopbag
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bopbag
  namespace: bopbag
spec:
  serviceName: "bopbag-headless"
  replicas: 3
  selector:
    matchLabels:
      app: bopbag
  template:
    metadata:
      labels:
        app: bopbag
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true" 
    spec:
      hostNetwork: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - bopbag
            topologyKey: "kubernetes.io/hostname"    
      containers:
        - name: bopbag
          image: balchu/bopbag:1.0.1
          imagePullPolicy: Always    
          ports:
          - containerPort: 8000
            name: web
          - containerPort: 9000
            name: dqlite
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name             
            - name: HEADLESS_SVC
              value: "bopbag-headless"
            - name: LIBRAFT_TRACE
              value: "1"
            - name: LIBDQLITE_TRACE
              value: "1"        
          volumeMounts:
          - name: data
            mountPath: /data
          - name: certs
            mountPath: /app/certs
      terminationGracePeriodSeconds: 10
      volumes:
        - name: certs
          secret:
            secretName: bopbag-certs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-path
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

