name: Build, Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Setup dependencies
        run: |
          sudo add-apt-repository ppa:dqlite/master -y
          sudo apt update
          sudo apt install -y golint libsqlite3-dev libuv1-dev liblz4-dev libraft-dev libdqlite-dev

      - name: Build
        env:
          CGO_LDFLAGS_ALLOW: "-Wl,-z,now"
        run: |
          go get -t -tags libsqlite3 ./...
          go vet -tags libsqlite3 ./...
          go build ./
      - name: Run coverage
        env:
          CGO_LDFLAGS_ALLOW: "-Wl,-z,now"      
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)